[package]
name = "timezones"
version = "0.1.0"
edition = "2024"

[dependencies]
array-deque = "0.3.1"
clap = { version = "4.5.58", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["display"] }
jiff = "0.2.20"
